[2023-02-24T03:57:15.302+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: ingest_bo_voucher_report.ingest_bo_voucher_report scheduled__2023-02-22T19:00:00+00:00 [queued]>
[2023-02-24T03:57:15.316+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: ingest_bo_voucher_report.ingest_bo_voucher_report scheduled__2023-02-22T19:00:00+00:00 [queued]>
[2023-02-24T03:57:15.317+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2023-02-24T03:57:15.318+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 4 of 7
[2023-02-24T03:57:15.320+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2023-02-24T03:57:15.339+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): ingest_bo_voucher_report> on 2023-02-22 19:00:00+00:00
[2023-02-24T03:57:15.344+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 462 to run task
[2023-02-24T03:57:15.349+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'ingest_bo_voucher_report', 'ingest_bo_voucher_report', 'scheduled__2023-02-22T19:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/ingest_bo_voucher_report.py', '--cfg-path', '/tmp/tmpdffdh_iz']
[2023-02-24T03:57:15.352+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 5: Subtask ingest_bo_voucher_report
[2023-02-24T03:57:15.429+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: ingest_bo_voucher_report.ingest_bo_voucher_report scheduled__2023-02-22T19:00:00+00:00 [running]> on host 8d8c6b853c06
[2023-02-24T03:57:15.502+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=ingest_bo_voucher_report
AIRFLOW_CTX_TASK_ID=ingest_bo_voucher_report
AIRFLOW_CTX_EXECUTION_DATE=2023-02-22T19:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-22T19:00:00+00:00
[2023-02-24T03:57:15.522+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/processing/ingest_bo_voucher_report.py", line 65, in ingest_bo_voucher_report
    spread = config_gg_sheet()
  File "/airflow/dags/processing/ingest_bo_voucher_report.py", line 16, in config_gg_sheet
    c = conf.get_config(path, "credentials.json")
  File "/opt/bitnami/python/lib/python3.8/site-packages/gspread_pandas/conf.py", line 88, in get_config
    raise IOError(
OSError: No Google client config found.
Please download json from https://console.developers.google.com/apis/credentials and save as /airflowairflow/dags/config/credentials.json
[2023-02-24T03:57:15.530+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=ingest_bo_voucher_report, task_id=ingest_bo_voucher_report, execution_date=20230222T190000, start_date=20230224T035715, end_date=20230224T035715
[2023-02-24T03:57:15.543+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 5 for task ingest_bo_voucher_report (No Google client config found.
Please download json from https://console.developers.google.com/apis/credentials and save as /airflowairflow/dags/config/credentials.json; 462)
[2023-02-24T03:57:15.563+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2023-02-24T03:57:15.579+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
