[2023-02-24T03:54:51.887+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: ingest_bo_voucher_report.ingest_bo_voucher_report scheduled__2023-02-22T19:00:00+00:00 [queued]>
[2023-02-24T03:54:51.897+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: ingest_bo_voucher_report.ingest_bo_voucher_report scheduled__2023-02-22T19:00:00+00:00 [queued]>
[2023-02-24T03:54:51.898+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2023-02-24T03:54:51.899+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 3 of 6
[2023-02-24T03:54:51.900+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2023-02-24T03:54:51.915+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): ingest_bo_voucher_report> on 2023-02-22 19:00:00+00:00
[2023-02-24T03:54:51.919+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 433 to run task
[2023-02-24T03:54:51.923+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'ingest_bo_voucher_report', 'ingest_bo_voucher_report', 'scheduled__2023-02-22T19:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/ingest_bo_voucher_report.py', '--cfg-path', '/tmp/tmpmij4qrmz']
[2023-02-24T03:54:51.926+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 4: Subtask ingest_bo_voucher_report
[2023-02-24T03:54:51.988+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: ingest_bo_voucher_report.ingest_bo_voucher_report scheduled__2023-02-22T19:00:00+00:00 [running]> on host 8d8c6b853c06
[2023-02-24T03:54:52.054+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=ingest_bo_voucher_report
AIRFLOW_CTX_TASK_ID=ingest_bo_voucher_report
AIRFLOW_CTX_EXECUTION_DATE=2023-02-22T19:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-22T19:00:00+00:00
[2023-02-24T03:54:52.069+0000] {logging_mixin.py:137} INFO - ðŸ¤ª /airflow
[2023-02-24T03:54:52.070+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/processing/ingest_bo_voucher_report.py", line 66, in ingest_bo_voucher_report
    spread = config_gg_sheet()
  File "/airflow/dags/processing/ingest_bo_voucher_report.py", line 13, in config_gg_sheet
    path = path[0:path.index('build_simple_dwh')] + "build_simple_dwh/airflow/dags/config/"
ValueError: substring not found
[2023-02-24T03:54:52.077+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=ingest_bo_voucher_report, task_id=ingest_bo_voucher_report, execution_date=20230222T190000, start_date=20230224T035451, end_date=20230224T035452
[2023-02-24T03:54:52.093+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 4 for task ingest_bo_voucher_report (substring not found; 433)
[2023-02-24T03:54:52.137+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2023-02-24T03:54:52.157+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
